### ISSUE TITLE
Things missing from Data Book

### ISSUE THREAD

**Issue by galenlynch** [AllenSWDB/allenswdb.github.io#21]
Just creating an issue to track the issues brought up on slack:

- [ ] Primer on the cortical microcircuit and cell types
- [x] Background on ISI (resolved by #17 and #18)
- [x] Background on calcium imaging, and two-photon excitation calcium imaging (resolved by #19)
- [x] Make cheat sheets more prominent  (addressed by 4cc17133f6251eb67dc9971c25009d2d5cbbe9a0)
- [x] Add Yoni's head frame material (#20)
- [ ] Explain differences & similarities between VBO and VBN datasets
- [ ] Show how to view images from the Visual Coding Neuropixels dataset

 Feel free to add more

**Comment by galenlynch** [comment]
I think @alakunina is working on a primer on cortical microcircuit and cell types
